version: '3.5'
services:
  node:
    build: .
    image: p2pchatapp
    command: 'node index.js 3000'
    # volumes:
    #   - .:/usr/app
    ports: 
      - 3000
    networks: 
      - socket-net

networks:
  socket-net: